### PR TITLE
Leaderboard Change Tracking

### PR DESCRIPTION
**Pull request by lseper**
Adds a feature to the leaderboard that says how much a player has "risen" or "fallen" in the rankings compared to the previous round.

### CODE REVIEW

**Comment by heroldev** [comment]
image_2022-05-05_201328177

upon creating a new tournament and only entering scores for the first round a "change" column still showed up, is this intentional (assuming it is using initial seeding for the change)

**Comment by lseper** [comment]
> image_2022-05-05_201328177
> 
> upon creating a new tournament and only entering scores for the first round a "change" column still showed up, is this intentional? (assuming it is using initial seeding for the change) for reference, scores were only for the first round and the round hadn't been completed yet

Yes, due to the way we set up `store.ts`, I was forced to have it updated as soon as any round was submitted (not just the entire round). I tried for a while to get it working to only show change after each completed round (i.e, waiting for ALL races to be finished) but it was far too much of a nightmare.

**Comment by heroldev** [comment]
> Yes, due to the way we set up `store.ts`, I was forced to have it updated as soon as any round was submitted (not just the entire round). I tried for a while to get it working to only show change after each completed round (i.e, waiting for ALL races to be finished) but it was far too much of a nightmare.

cool, looks good to me then 🚀

**Review by heroldev — APPROVED** [review]

**Comment by lseper** [comment]
LETS FUCKING GO WE GOT IT WORKING TO ONLY SHOW WHEN FULL ROUNDS ARE COMPLETED 🚀🚀🚀🚀🚀🚀🚀🚀

Thanks to @danielnoon for fixing a bug with the leaderboard context switching when you switch tournaments

**Comment by heroldev** [comment]
why the vercel build fail

**Comment by lseper** [comment]
> why the vercel build fail

D:

**Comment by lseper** [comment]
> > why the vercel build fail

D:

Fucking unit tests are failing god dammit

**Review by heroldev — APPROVED** [review]
LGTM 🚀

**Pull request merged**
