### PR TITLE
Add basic test menu and course generation test page

### PR DESCRIPTION
**Pull request by heroldev**
## Feature Description

- adds a test menu accessible via the create page (can be moved or hidden), ideally to add more UI tests in the future
- adds a test page for testing the course generation algorithm

## Testing Instructions
- test the test page (lol)
## Required local store changes (If Needed)
`no storage changes necessary`
## PR Checklist
- [ ] Feature works on Firefox and Chrome
- [ ] Feature works on mobile
- [ ] JS version param updated/cache busting (if needed)

### CODE REVIEW

**Comment by lseper** [comment]
Looks good, but why not add unit tests instead of a dedicated page?

**Comment by heroldev** [comment]
Unit tests are already present for course generation, but I wanted an accessible page to quickly check the end result of course generation for difficulty assignment purposes using a custom, user-defined threshold. 

The already present unit tests use a random threshold, similar to how it's used in prod.

**Review by lseper — COMMENTED** [review]
StandingOvationGIF

**Comment by lseper** [comment]
Ah that makes sense then, LGTM 👍

**Comment by heroldev** [comment]
line 808 of `algorithms.test.ts` is where the course generation and threshold tests reside

**Pull request merged**
