### PR TITLE
Consistent course generation across setups in a round

### PR DESCRIPTION
**Pull request by heroldev**
## Feature Description
- course generation is now consistent for each setup in a given round
## Testing Instructions
- test course generation and verify each setup has the same courses in a round, and that it changes across rounds
## Required local store changes (If Needed)
`no storage changes necessary`
## PR Checklist
- [ ] Feature works on Firefox and Chrome
- [ ] Feature works on mobile
- [ ] JS version param updated/cache busting (if needed)

### CODE REVIEW

**Comment by lseper** [comment]
Looks good, ideally having this be a togglable feature would be nice so that users can choose between having the same course vs. different courses for each round. But for now, LGTM 👍

**Comment by heroldev** [comment]
I think that it doesn't need to be togglable because we want the points to be an assessment of the competitors performance, and having different courses between setups in a round causes a discrepancy between the matches. If we wanted it to be togglable then we'd need to put in a sort of "strength of schedule" variable since courses are inherently harder than others.

The functionality of this PR is to enable all setups across a round to have the same course selection to ensure that the points are truly representative of the competitors, and eliminate outside factors from scoring such as an easy or hard course selection.

**Comment by lseper** [comment]
> You've actually given me an idea. I'm gonna wait to merge this one

Are we still wanting to implement a change of some kind?

**Comment by heroldev** [comment]
> Are we still wanting to implement a change of some kind?

Lol yeah, just got busy with other things. I remember what I wanted to do though

**Pull request merged**
